---
title: "Schmid Lab Final ONPG Calculations and Statistical Analyses"
author: "Katie Lam & Rylee Hackley"
project: "HVO trmB and tbsP"
output: github_document
---

```{r setup, load packages, message = FALSE}
library(tidyverse)
library(janitor)
library(plotrix)
library(ggpubr)
library(rstatix)
library(readxl)
```

```{r functions}
makeDF <- function(x, expt, rep) {
  onpg <- x[, c(2, 3, 6)]
  colnames(onpg)[3] <- "Absorbance"
  reformat <- onpg %>%
    pivot_wider(names_from = Repeat, values_from = Absorbance) %>%
    t(.) # names_from = columns, values_from = data
  reformat <- row_to_names(reformat, row_number = 1, remove_row = TRUE)
  reformat <- reformat %>%
    as.data.frame() %>%
    mutate(
      "time" = c(1:20),
      "expt" = expt,
      "replicate" = rep) %>%
    mutate_if(is.character, as.numeric)

  pdf(paste("plots/", expt, "_", rep, "_ONPG.pdf", sep = ""), height = 8.5, width = 11)
  for (j in 1:72) {
    well <- reformat[c(j, 97)]
    well <- well %>% filter(time > 1 & time < 7)
    well_name <- names(well[1])

    print(ggplot(well, aes(x = time, y = .data[[well_name]])) +
      geom_point() +
      geom_smooth(method = lm, se = FALSE) +
      stat_regline_equation(label.y = 0.2, aes(label = ..eq.label..)) +
      labs(title = well_name) +
      stat_regline_equation(label.y = 0.1, aes(label = ..rr.label..)))
  }
  dev.off()
  return(reformat)
}

enzyme_act <- function(onpg, bradford_col, wells, time_initial, time_final, assay_duration) {
  # subtract time
  onpgtime <- onpg[c(time_initial, time_final), ] %>%
    t(.) %>%
    as.data.frame()
  onpgtime$OD405nm <- (onpgtime[[2]] - onpgtime[[1]])

  # ONP calculation
  onpg_final <- onpgtime[1:wells,] %>%
    mutate(ONP_vol = (OD405nm * 0.1) / (3300 * 0.29 * 0.04)) %>% 
    # 0.29cm path length adjustment for 100ul in 96 well plate.
    # 3300 - ONP molar extinction coefficient (pH dependent).
    # 0.1 mL for total volume. 0.04mL of enzyme lysate volume.
    mutate(ONP_vol_time = ONP_vol / assay_duration) # ONP calculation divided by minutes between first and last measurements used
  prot <- bradford_col[1:wells]
  onpg_final <- cbind(onpg_final, prot) %>%
    mutate(normalize_protein = ONP_vol_time / prot) %>% # enzymatic activity per ug of lysate
    mutate(BgaH_activity = normalize_protein * 1000 * 1000) # unit conversion from mol to umol
  onpg_final <- rownames_to_column(onpg_final, var = "well")
  return(onpg_final)
}
```

##Reformatting
### Reformats the raw data to wide format, with the time point in rows, and the plate wells as the column titles. Each number represents the absorbance value measured by the plate reader. Also graphs the increase in absorbance over time to identitfy linear ranges.
```{r import data, message=FALSE}
# load input protein
bradford <- read_csv("metadata_all.csv")

filenames <- list.files(path = "ONPG_raw/", pattern = ".xls")
label <- str_remove_all(filenames, "[:alpha:]") %>%
  str_remove_all(., "\\.") %>%
  str_replace(., "2022", "onpg_2022")
expts <- str_extract(filenames, "^[:digit:]{8}")
reps <- as.numeric(str_sub(filenames, 14, 14))
```

```{r read data}
for (i in 1:length(filenames)) {
  tmp <- read_xls(paste("ONPG_raw/", filenames[i], sep = ""))
  assign(label[i], makeDF(tmp, expts[i], reps[i]), inherits = )
}
```

## sept 27 calculations
```{r sept calculations, warningr = FALSE, message = FALSE}
bradfordsept <- bradford %>% filter(date == 20220927)

sept3 <- enzyme_act(onpg_20220927_1, bradfordsept$lysate_mass, 72, 2, 9, 14) 
sept4 <- enzyme_act(onpg_20220927_2, bradfordsept$lysate_mass, 72, 2, 9, 14)
sept5 <- enzyme_act(onpg_20220927_3, bradfordsept$lysate_mass, 72, 2, 9, 14)

#put all data frames into list
df_list <- list(sept3[c(1,9)], sept4[c(1,9)], sept5[c(1,9)])

#merge all data frames in list
sept <- df_list %>% purrr::reduce(full_join, by='well')

# combine trials
meta_sept <- left_join(bradfordsept, sept, by = "well") %>%
  filter(strain != "blank")
write_csv(meta_sept, "motility_supp.csv")

#long
meta_sept_long <- pivot_longer(meta_sept, cols = 10:12)

#average across bioreps, then SD across technical reps
meta_sept_stat <- meta_sept_long %>%
  group_by(condition, strain, promoter, name) %>%
  summarize(avg_OD = mean(value)) %>% ## value is enzymatic activity
  group_by(condition, strain, promoter) %>%
  summarize(avgOD= mean(avg_OD), biorepSD = sd(avg_OD))

group.colors <- c(parent = "magenta4", trmB ="#35B779", trmBtbsP ="#A6A560", tbsP ="#E79A51")

meta_sept_stat %>%
  ggplot(aes(x = strain, y = avgOD, fill = strain)) +
  geom_col(position = position_dodge(0.8), width = .7, color = "black") +
  geom_errorbar(aes(ymin = avgOD- biorepSD, ymax = avgOD + biorepSD), 
                position = position_dodge(0.8), width = .4) +
  facet_grid(promoter~condition, scales = "free") +
  #coord_flip()+
  scale_fill_manual(values = group.colors)+
  labs(y = "B-galactosidase activity (mU)")+
  theme(legend.position = "none", axis.text.x = element_text(angle = 45, vjust = 0.7))  -> bgah
bgah

#pdf("gapII_all.pdf", width = 3, height = 6.5)
#bgah
#dev.off()
```

```{r, warning = FALSE, message = FALSE}
norms.hvo <- meta_sept_long %>%
  group_by(condition, strain, promoter, name) %>%
  summarize(avg_OD = mean(value))

norms.hvo %>%
  filter(promoter == "gapII") -> norms2
vals <- norms2 %>%
  group_by(condition) %>%
  t_test(avg_OD ~ strain, ref.group = "parent", p.adjust.method = "BH") %>%
  add_y_position(fun = "mean_se")
ggbarplot(norms2, x = "strain", y = "avg_OD",
          fill = "strain", add = "mean_se",
          facet.by = c("condition"), 
          position = position_dodge(0.9), size = 0.8, ylab = "B-galactosidase activity (mU)") +
  stat_pvalue_manual(vals,  label = "p.adj.signif", tip.length = 0) +
  scale_color_manual(values = group.colors, aesthetics = c("fill")) +
  theme_grey()+
  theme(
    axis.title.y = element_text(size = 12, angle = 90),
    axis.text.y = element_text(size = 12, angle = 0), 
    axis.text.x = element_text(angle = 45, vjust = 0.7),
    axis.title.x = element_blank(),
    axis.ticks.length.y.left = unit(.05, "cm"), 
    strip.text = element_text(size = 12),
    strip.placement = "outside",
    legend.position = "none") -> bgah
pdf("gapII_bgaH.pdf", width = 5, height = 3)
bgah
dev.off()

norms.hvo %>%
  filter(promoter == "EV") -> norms3
vals <- norms3 %>%
  group_by(condition) %>%
  t_test(avg_OD ~ strain, ref.group = "parent", p.adjust.method = "BH") %>%
  add_y_position(fun = "mean_se")
ggbarplot(norms3, x = "strain", y = "avg_OD",
          fill = "strain", add = "mean_se",
          facet.by = c("condition"), 
          position = position_dodge(0.9), size = 0.8, ylab = "B-galactosidase activity (mU)") +
  stat_pvalue_manual(vals,  label = "p.adj.signif", tip.length = 0) +
  scale_color_manual(values = group.colors, aesthetics = c("fill")) +
  theme_grey()+
  theme(
    axis.title.y = element_text(size = 12, angle = 90),
    axis.text.y = element_text(size = 12, angle = 0), 
    axis.text.x = element_text(angle = 45, vjust = 0.7),
    axis.title.x = element_blank(),
    axis.ticks.length.y.left = unit(.05, "cm"), 
    strip.text = element_text(size = 12),
    strip.placement = "outside",
    legend.position = "none") -> bgah
pdf("EV_bgaH.pdf", width = 5, height = 3)
bgah
dev.off()

norms.hvo %>%
  filter(promoter == "+ctrl") -> norms4
vals <- norms4 %>%
  group_by(condition) %>%
  t_test(avg_OD ~ strain, ref.group = "parent", p.adjust.method = "BH") %>%
  add_y_position(fun = "mean_se")
ggbarplot(norms4, x = "strain", y = "avg_OD",
          fill = "strain", add = "mean_se",
          facet.by = c("condition"), 
          position = position_dodge(0.9), size = 0.8, ylab = "B-galactosidase activity (mU)") +
  stat_pvalue_manual(vals,  label = "p.adj.signif", tip.length = 0) +
  scale_color_manual(values = group.colors, aesthetics = c("fill")) +
  theme_grey()+
 theme(
    axis.title.y = element_text(size = 12, angle = 90),
    axis.text.y = element_text(size = 12, angle = 0), 
    axis.text.x = element_text(angle = 45, vjust = 0.7),
    axis.title.x = element_blank(),
    axis.ticks.length.y.left = unit(.05, "cm"), 
    strip.text = element_text(size = 12),
    strip.placement = "outside",
    legend.position = "none") -> bgah
pdf("pR2_bgaH.pdf", width = 5, height = 3)
bgah
dev.off()

vals2 <- norms2 %>%
  group_by(strain, promoter) %>%
  t_test(avg_OD ~ condition, alternative = "greater", p.adjust.method = "BH") %>% 
  add_y_position(fun = "mean_se")
ggbarplot(norms2, x = "condition", y = "avg_OD",
          fill = "strain", add = "mean_se",
          position = position_dodge(0.9), size = 0.8, ylab = "B-galactosidase activity (mU)") +
  stat_pvalue_manual(vals2,  label = "p", tip.length = 0) +
  scale_color_manual(values = group.colors, aesthetics = c("fill")) +
  theme_grey()+
  theme(
    axis.title.y = element_text(size = 12, angle = 90),
    axis.text.y = element_text(size = 12, angle = 0), 
    axis.ticks.length.y.left = unit(.05, "cm"), 
    strip.text = element_text(size = 12),
    strip.placement = "outside",
    legend.position = "none") -> bgah
facet(bgah, facet.by = c("strain"), nrow = 1) -> bgah
pdf("gapII_bgaH_glu.pdf", width = 5, height = 3)
bgah
dev.off()
```
